import { Conference } from "./types";

// Static conference data — no database needed for static export / GitHub Pages deployment
// Conferences that have fully passed are replaced with next year's edition.

// Cache the conference array so IDs are stable across calls
let _cachedConferences: Conference[] | null = null;

function buildConferences(): Conference[] {
    let nextId = 1;
    function id() {
        return nextId++;
    }
    return [
        // ===== AI/ML Conferences =====
        // ICLR 2026 — Official: iclr.cc
        // Conference: Apr 23–27, Rio de Janeiro, Brazil
        {
            id: id(),
            name: "International Conference on Learning Representations",
            short_name: "ICLR",
            year: 2026,
            area: "AI/ML",
            rating: "A*",
            rating_source: "CORE",
            conference_start_date: "2026-04-23",
            conference_end_date: "2026-04-27",
            submission_start_date: "2025-09-19",
            submission_deadline: "2025-09-24",
            notification_date: "2026-01-25",
            camera_ready_date: "2026-03-14",
            workshop_date: "2026-04-26",
            tutorial_date: "2026-04-23",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Rio de Janeiro",
            country: "Brazil",
            venue: "Riocentro Convention Center",
            timezone: "America/Sao_Paulo",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 10,
            submission_types: ["long paper", "short paper", "poster"],
            h5_index: 332,
            h5_median: 565,
            acceptance_rate: 32.0,
            historical_acceptance_rates: { "2025": 32.0, "2024": 31.0, "2023": 32.0, "2022": 32.3 },
            total_submissions: null,
            total_accepted: null,
            website: "https://iclr.cc/Conferences/2026",
            cfp_url: "https://iclr.cc/Conferences/2026/CallForPapers",
            proceedings_url: "https://openreview.net/group?id=ICLR.cc/2025/Conference",
            paper_template_url: "https://github.com/ICLR/Master-Template",
            latex_template_url: null,
            themes: ["Representation Learning", "Deep Learning", "Generative Models", "Reinforcement Learning"],
            tracks: ["Main Conference", "Workshop", "Tiny Papers"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "OpenReview",
            open_access: true,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // NeurIPS 2026 — Official: neurips.cc
        // Conference: Dec 6–12, Sydney, Australia
        {
            id: id(),
            name: "Conference on Neural Information Processing Systems",
            short_name: "NeurIPS",
            year: 2026,
            area: "AI/ML",
            rating: "A*",
            rating_source: "CORE",
            conference_start_date: "2026-12-06",
            conference_end_date: "2026-12-12",
            submission_start_date: "2026-05-04",
            submission_deadline: "2026-05-06",
            notification_date: "2026-09-24",
            camera_ready_date: "2026-10-31",
            workshop_date: "2026-12-11",
            tutorial_date: "2026-12-06",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Sydney",
            country: "Australia",
            venue: "International Convention Centre Sydney",
            timezone: "Australia/Sydney",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 10,
            submission_types: ["long paper", "poster", "spotlight", "datasets & benchmarks"],
            h5_index: 309,
            h5_median: 530,
            acceptance_rate: 25.8,
            historical_acceptance_rates: { "2025": 25.8, "2024": 25.8, "2023": 26.1, "2022": 25.6 },
            total_submissions: null,
            total_accepted: null,
            website: "https://neurips.cc/Conferences/2026",
            cfp_url: "https://neurips.cc/Conferences/2026/CallForPapers",
            proceedings_url: "https://proceedings.neurips.cc/paper_files/paper/2025",
            paper_template_url: "https://neurips.cc/Conferences/2026/PaperInformation/StyleFiles",
            latex_template_url: null,
            themes: ["Machine Learning", "Neuroscience", "Optimization", "Theory"],
            tracks: ["Main Conference", "Datasets & Benchmarks", "Workshop"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "NeurIPS Proceedings",
            open_access: true,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // ICML 2026 — Official: icml.cc
        // Conference: Jul 6–11, Seoul, South Korea
        {
            id: id(),
            name: "International Conference on Machine Learning",
            short_name: "ICML",
            year: 2026,
            area: "AI/ML",
            rating: "A*",
            rating_source: "CORE",
            conference_start_date: "2026-07-06",
            conference_end_date: "2026-07-11",
            submission_start_date: "2026-01-08",
            submission_deadline: "2026-01-28",
            notification_date: "2026-04-30",
            camera_ready_date: "2026-06-05",
            workshop_date: "2026-07-10",
            tutorial_date: "2026-07-06",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Seoul",
            country: "South Korea",
            venue: "COEX Convention Center",
            timezone: "Asia/Seoul",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 10,
            submission_types: ["long paper", "poster", "spotlight"],
            h5_index: 268,
            h5_median: 474,
            acceptance_rate: 27.9,
            historical_acceptance_rates: { "2025": 27.9, "2024": 27.5, "2023": 27.9, "2022": 21.9 },
            total_submissions: null,
            total_accepted: null,
            website: "https://icml.cc/Conferences/2026",
            cfp_url: "https://icml.cc/Conferences/2026/CallForPapers",
            proceedings_url: "https://proceedings.mlr.press/v267",
            paper_template_url: "https://icml.cc/Conferences/2026/StyleFiles",
            latex_template_url: null,
            themes: ["Machine Learning", "Deep Learning", "Optimization", "Theory"],
            tracks: ["Main Conference", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "PMLR",
            open_access: true,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // AAAI 2027 — Official: aaai.org/conference/aaai/
        // AAAI 2026 (Jan 20-27, Singapore) has already passed.
        // AAAI 2027: Feb 16–23, 2027, Montréal, Québec, Canada (41st conference)
        // Deadlines estimated from 2026 cycle patterns (~6 months before conference)
        {
            id: id(),
            name: "AAAI Conference on Artificial Intelligence",
            short_name: "AAAI",
            year: 2027,
            area: "AI/ML",
            rating: "A*",
            rating_source: "CCF",
            conference_start_date: "2027-02-16",
            conference_end_date: "2027-02-23",
            submission_start_date: "2026-06-15",
            submission_deadline: "2026-08-01",
            notification_date: "2026-11-10",
            camera_ready_date: "2026-11-20",
            workshop_date: "2027-02-22",
            tutorial_date: "2027-02-16",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: "2026-07-25",
            city: "Montréal",
            country: "Canada",
            venue: "Palais des congrès de Montréal",
            timezone: "America/Montreal",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 8,
            submission_types: ["long paper", "short paper", "demo", "student abstract"],
            h5_index: 212,
            h5_median: 330,
            acceptance_rate: 23.4,
            historical_acceptance_rates: { "2026": 23.4, "2025": 23.4, "2024": 23.7, "2023": 19.6 },
            total_submissions: null,
            total_accepted: null,
            website: "https://aaai.org/conference/aaai/",
            cfp_url: null,
            proceedings_url: "https://ojs.aaai.org/index.php/AAAI/issue/view/683",
            paper_template_url: "https://aaai.org/authorkit/",
            latex_template_url: null,
            themes: ["Artificial Intelligence", "NLP", "Computer Vision", "Robotics", "Knowledge Representation"],
            tracks: ["Main Track", "Special Track", "Demo", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "AAAI Press",
            open_access: true,
            paper_download_url: null,
            is_favorite: false,
            notes: "Dates confirmed from aaai.org. Submission deadlines estimated from 2026 cycle.",
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },

        // ===== Systems Conferences =====
        // MLSys 2026 — Official: mlsys.org
        // Conference: May 18–22, Bellevue, WA
        {
            id: id(),
            name: "Conference on Machine Learning and Systems",
            short_name: "MLSys",
            year: 2026,
            area: "Systems",
            rating: "A",
            rating_source: "Community",
            conference_start_date: "2026-05-18",
            conference_end_date: "2026-05-22",
            submission_start_date: "2025-09-15",
            submission_deadline: "2025-10-30",
            notification_date: "2026-01-26",
            camera_ready_date: "2026-04-01",
            workshop_date: "2026-05-22",
            tutorial_date: "2026-05-18",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Bellevue",
            country: "USA",
            venue: "Meydenbauer Center",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper", "poster"],
            h5_index: 67,
            h5_median: 113,
            acceptance_rate: 24.0,
            historical_acceptance_rates: { "2025": 24.0, "2024": 22.0, "2023": 25.0, "2022": 20.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://mlsys.org/",
            cfp_url: "https://mlsys.org/Conferences/2026/CallForPapers",
            proceedings_url: "https://proceedings.mlsys.org/papers/2025",
            paper_template_url: "https://mlsys.org/Conferences/2026/StyleFiles",
            latex_template_url: null,
            themes: ["ML Systems", "Compiler Optimization", "Distributed Training", "Inference"],
            tracks: ["Main Conference", "Workshop"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "MLSys",
            open_access: true,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // OSDI 2026 — Official: usenix.org
        // Conference: Jul 13–15, Seattle, WA
        {
            id: id(),
            name: "USENIX Symposium on Operating Systems Design and Implementation",
            short_name: "OSDI",
            year: 2026,
            area: "Systems",
            rating: "A*",
            rating_source: "CCF",
            conference_start_date: "2026-07-13",
            conference_end_date: "2026-07-15",
            submission_start_date: "2025-12-04",
            submission_deadline: "2025-12-11",
            notification_date: "2026-03-26",
            camera_ready_date: "2026-06-09",
            workshop_date: null,
            tutorial_date: null,
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Seattle",
            country: "USA",
            venue: "TBD",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper"],
            h5_index: 76,
            h5_median: 133,
            acceptance_rate: 18.5,
            historical_acceptance_rates: { "2024": 18.5, "2023": 19.0, "2022": 17.9, "2021": 18.8 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.usenix.org/conference/osdi26",
            cfp_url: "https://www.usenix.org/conference/osdi26/call-for-papers",
            proceedings_url: "https://www.usenix.org/conference/osdi24/technical-sessions",
            paper_template_url: "https://www.usenix.org/conferences/author-resources/paper-templates",
            latex_template_url: null,
            themes: ["Operating Systems", "Distributed Systems", "Storage", "Networking", "ML Systems"],
            tracks: ["Research Track", "Operational Systems Track"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "USENIX",
            open_access: true,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // SOSP 2026 — Official: sigops.org
        // Conference: Sep 29 – Oct 2, Prague, Czechia
        {
            id: id(),
            name: "ACM Symposium on Operating Systems Principles",
            short_name: "SOSP",
            year: 2026,
            area: "Systems",
            rating: "A*",
            rating_source: "CCF",
            conference_start_date: "2026-09-29",
            conference_end_date: "2026-10-02",
            submission_start_date: "2026-03-26",
            submission_deadline: "2026-04-01",
            notification_date: "2026-07-03",
            camera_ready_date: "2026-08-28",
            workshop_date: "2026-09-29",
            tutorial_date: null,
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Prague",
            country: "Czechia",
            venue: "Clarion Congress Hotel Prague",
            timezone: "Europe/Prague",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper"],
            h5_index: 56,
            h5_median: 100,
            acceptance_rate: 17.5,
            historical_acceptance_rates: { "2025": 17.5, "2023": 17.4, "2021": 18.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://sigops.org/s/conferences/sosp/2026/",
            cfp_url: "https://sigops.org/s/conferences/sosp/2026/cfp.html",
            proceedings_url: "https://dl.acm.org/doi/proceedings/10.1145/3694715",
            paper_template_url: "https://www.acm.org/publications/proceedings-template",
            latex_template_url: null,
            themes: ["Operating Systems", "Distributed Systems", "Verification", "Security"],
            tracks: ["Main Conference", "Workshop"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // PACT 2026 — Official: pact2026.github.io
        // Conference: Oct 19–22, Chicago, IL
        {
            id: id(),
            name: "International Conference on Parallel Architectures and Compilation Techniques",
            short_name: "PACT",
            year: 2026,
            area: "Systems",
            rating: "A",
            rating_source: "CCF",
            conference_start_date: "2026-10-19",
            conference_end_date: "2026-10-22",
            submission_start_date: "2026-04-17",
            submission_deadline: "2026-04-24",
            notification_date: "2026-08-05",
            camera_ready_date: "2026-10-02",
            workshop_date: "2026-10-19",
            tutorial_date: "2026-10-19",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Chicago",
            country: "USA",
            venue: "TBD",
            timezone: "America/Chicago",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper", "short paper", "poster"],
            h5_index: 35,
            h5_median: 52,
            acceptance_rate: 25.0,
            historical_acceptance_rates: { "2025": 25.0, "2024": 24.5, "2023": 23.8, "2022": 25.2 },
            total_submissions: null,
            total_accepted: null,
            website: "https://pact2026.github.io/",
            cfp_url: "https://pact2026.github.io/cfp/",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000093/all-proceedings",
            paper_template_url: "https://www.acm.org/publications/proceedings-template",
            latex_template_url: null,
            themes: ["Parallel Computing", "Compiler Optimization", "Architecture", "Runtime Systems"],
            tracks: ["Main Conference", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },

        // ===== Hardware / Architecture Conferences =====
        // HPCA 2027 — HPCA 2026 (Jan 31–Feb 4, Sydney) has already passed.
        // HPCA 2027: Estimated late Jan/early Feb 2027 based on historical patterns.
        // HPCA alternates between different locations. Deadlines estimated from 2026 cycle.
        {
            id: id(),
            name: "IEEE International Symposium on High-Performance Computer Architecture",
            short_name: "HPCA",
            year: 2027,
            area: "Hardware",
            rating: "A",
            rating_source: "CCF",
            conference_start_date: "2027-02-06",
            conference_end_date: "2027-02-10",
            submission_start_date: "2026-07-15",
            submission_deadline: "2026-08-01",
            notification_date: "2026-11-15",
            camera_ready_date: "2027-01-15",
            workshop_date: "2027-02-06",
            tutorial_date: "2027-02-06",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "TBD",
            country: "TBD",
            venue: "TBD",
            timezone: null,
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper"],
            h5_index: 60,
            h5_median: 93,
            acceptance_rate: 22.8,
            historical_acceptance_rates: { "2026": 22.8, "2025": 22.8, "2024": 24.2, "2023": 25.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://hpca-conf.org/",
            cfp_url: null,
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000014/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Computer Architecture", "Microarchitecture", "Memory Systems", "Accelerators"],
            tracks: ["Main Conference", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: true,
            notes: "HPCA 2027 dates and location TBD. Deadlines estimated from 2026 cycle.",
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // ISCA 2026 — Official: iscaconf.org/isca2026/
        // Conference: Jun 27 – Jul 1, 2026, Raleigh, NC, USA
        {
            id: id(),
            name: "International Symposium on Computer Architecture",
            short_name: "ISCA",
            year: 2026,
            area: "Hardware",
            rating: "A*",
            rating_source: "CCF",
            conference_start_date: "2026-06-27",
            conference_end_date: "2026-07-01",
            submission_start_date: "2025-11-10",
            submission_deadline: "2025-11-17",
            notification_date: "2026-03-27",
            camera_ready_date: "2026-05-15",
            workshop_date: "2026-06-27",
            tutorial_date: "2026-06-27",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Raleigh",
            country: "USA",
            venue: "Raleigh Convention Center",
            timezone: "America/New_York",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper"],
            h5_index: 72,
            h5_median: 120,
            acceptance_rate: 22.0,
            historical_acceptance_rates: { "2025": 22.0, "2024": 21.5, "2023": 22.2, "2022": 20.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://iscaconf.org/isca2026/",
            cfp_url: "https://iscaconf.org/isca2026/cfp/",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000122/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Computer Architecture", "Accelerators", "Memory", "Interconnect"],
            tracks: ["Main Conference", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // MICRO 2026 (59th) — Official: microarch.org/micro59/
        // Conference: Oct 31 – Nov 4, Athens, Greece
        {
            id: id(),
            name: "IEEE/ACM International Symposium on Microarchitecture",
            short_name: "MICRO",
            year: 2026,
            area: "Hardware",
            rating: "A*",
            rating_source: "CCF",
            conference_start_date: "2026-10-31",
            conference_end_date: "2026-11-04",
            submission_start_date: "2026-03-31",
            submission_deadline: "2026-04-07",
            notification_date: "2026-07-07",
            camera_ready_date: "2026-09-11",
            workshop_date: "2026-10-31",
            tutorial_date: "2026-10-31",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Athens",
            country: "Greece",
            venue: "TBD",
            timezone: "Europe/Athens",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 12,
            submission_types: ["long paper"],
            h5_index: 65,
            h5_median: 106,
            acceptance_rate: 22.5,
            historical_acceptance_rates: { "2025": 22.5, "2024": 22.0, "2023": 22.4, "2022": 20.9 },
            total_submissions: null,
            total_accepted: null,
            website: "https://microarch.org/micro59/",
            cfp_url: "https://microarch.org/micro59/cfp/",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000088/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Microarchitecture", "Processors", "Accelerators", "Security"],
            tracks: ["Main Conference", "Workshop", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },

        // ===== EDA / VLSI Conferences =====
        // ICCAD 2026 — Official: iccad.com
        // Conference: Nov 8–12, San Jose, California
        {
            id: id(),
            name: "International Conference on Computer-Aided Design",
            short_name: "ICCAD",
            year: 2026,
            area: "EDA/VLSI",
            rating: "A",
            rating_source: "CCF",
            conference_start_date: "2026-11-08",
            conference_end_date: "2026-11-12",
            submission_start_date: "2026-04-07",
            submission_deadline: "2026-04-14",
            notification_date: "2026-07-11",
            camera_ready_date: "2026-08-24",
            workshop_date: "2026-11-08",
            tutorial_date: "2026-11-08",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "San Jose",
            country: "USA",
            venue: "San Jose McEnery Convention Center",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 8,
            submission_types: ["long paper", "short paper", "poster"],
            h5_index: 45,
            h5_median: 65,
            acceptance_rate: 24.0,
            historical_acceptance_rates: { "2025": 24.0, "2024": 23.5, "2023": 24.3, "2022": 22.1 },
            total_submissions: null,
            total_accepted: null,
            website: "https://iccad.com/",
            cfp_url: "https://iccad.com/call_for_papers",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000155/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["EDA", "Logic Synthesis", "Physical Design", "Verification", "ML for EDA"],
            tracks: ["Main Conference", "Workshop", "Contest"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // DATE 2026 — Official: date-conference.com
        // Conference: Apr 20–22, Verona, Italy
        {
            id: id(),
            name: "Design, Automation and Test in Europe",
            short_name: "DATE",
            year: 2026,
            area: "EDA/VLSI",
            rating: "A",
            rating_source: "CCF",
            conference_start_date: "2026-04-20",
            conference_end_date: "2026-04-22",
            submission_start_date: "2025-09-07",
            submission_deadline: "2025-09-14",
            notification_date: "2025-11-10",
            camera_ready_date: "2026-01-16",
            workshop_date: "2026-04-20",
            tutorial_date: "2026-04-20",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Verona",
            country: "Italy",
            venue: "Verona Fiere",
            timezone: "Europe/Rome",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 6,
            submission_types: ["long paper", "extended abstract", "late breaking results"],
            h5_index: 52,
            h5_median: 71,
            acceptance_rate: 25.0,
            historical_acceptance_rates: { "2025": 25.0, "2024": 24.2, "2023": 25.5, "2022": 26.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.date-conference.com/",
            cfp_url: "https://www.date-conference.com/call-for-papers",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000192/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["EDA", "Embedded Systems", "Cyber-Physical Systems", "IoT"],
            tracks: ["Design Methods", "Applications", "Test", "Embedded Systems"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE/ACM",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // ASP-DAC 2027 — Official: aspdac.com/aspdac2027/
        // ASP-DAC 2026 (Jan 19–22, Hong Kong) has already passed.
        // ASP-DAC 2027: Jan 25–28, 2027, Hitotsubashi Hall, Tokyo, Japan
        // Abstract: Jul 3, 2026; Paper: Jul 10, 2026; Notification: Sep 4, 2026; Camera-ready: Oct 27, 2026
        {
            id: id(),
            name: "Asia and South Pacific Design Automation Conference",
            short_name: "ASP-DAC",
            year: 2027,
            area: "EDA/VLSI",
            rating: "B",
            rating_source: "CCF",
            conference_start_date: "2027-01-25",
            conference_end_date: "2027-01-28",
            submission_start_date: "2026-07-03",
            submission_deadline: "2026-07-10",
            notification_date: "2026-09-04",
            camera_ready_date: "2026-10-27",
            workshop_date: "2027-01-28",
            tutorial_date: "2027-01-25",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: "2026-07-03",
            city: "Tokyo",
            country: "Japan",
            venue: "Hitotsubashi Hall",
            timezone: "Asia/Tokyo",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 6,
            submission_types: ["long paper", "short paper", "poster"],
            h5_index: 30,
            h5_median: 42,
            acceptance_rate: 30.0,
            historical_acceptance_rates: { "2026": 30.0, "2025": 30.0, "2024": 29.5, "2023": 31.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.aspdac.com/aspdac2027/",
            cfp_url: "https://www.aspdac.com/aspdac2027/cfp/",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000197/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["VLSI Design", "EDA", "Embedded Systems", "Low Power", "AI for EDA"],
            tracks: ["Main Conference", "Workshop", "Tutorial", "Design Contest"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: "Dates and deadlines confirmed from official ASP-DAC 2027 CFP.",
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // DAC 2026 — Official: dac.com
        // Conference: Jul 26–29, Long Beach, CA
        {
            id: id(),
            name: "Design Automation Conference",
            short_name: "DAC",
            year: 2026,
            area: "EDA/VLSI",
            rating: "A",
            rating_source: "CCF",
            conference_start_date: "2026-07-26",
            conference_end_date: "2026-07-29",
            submission_start_date: "2025-09-30",
            submission_deadline: "2025-11-19",
            notification_date: "2026-03-09",
            camera_ready_date: "2026-04-14",
            workshop_date: "2026-07-26",
            tutorial_date: "2026-07-26",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Long Beach",
            country: "USA",
            venue: "Long Beach Convention Center",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "double-blind",
            paper_format: "LaTeX",
            max_pages: 6,
            submission_types: ["long paper", "late breaking results", "poster"],
            h5_index: 53,
            h5_median: 78,
            acceptance_rate: 23.0,
            historical_acceptance_rates: { "2025": 23.0, "2024": 22.5, "2023": 23.0, "2022": 23.7 },
            total_submissions: null,
            total_accepted: null,
            website: "https://dac.com/2026",
            cfp_url: "https://dac.com/2026/authors/call-for-contributions",
            proceedings_url: "https://dl.acm.org/doi/proceedings/10.1145/3649329",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Design Automation", "EDA", "AI", "Security", "Low Power", "Chiplets"],
            tracks: ["Research", "Late Breaking Results", "Engineering Track", "Exhibition"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "ACM/IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },

        // ===== Hardware / Semiconductor Conferences =====
        // ISSCC 2027 — ISSCC 2026 (Feb 15–19, San Francisco) has already passed.
        // ISSCC is held every February in San Francisco. ISSCC 2027 dates estimated.
        // Submission deadline typically ~Sep of previous year.
        {
            id: id(),
            name: "IEEE International Solid-State Circuits Conference",
            short_name: "ISSCC",
            year: 2027,
            area: "Hardware",
            rating: "A*",
            rating_source: "Community",
            conference_start_date: "2027-02-14",
            conference_end_date: "2027-02-18",
            submission_start_date: "2026-06-01",
            submission_deadline: "2026-09-08",
            notification_date: "2026-11-15",
            camera_ready_date: "2026-12-15",
            workshop_date: "2027-02-14",
            tutorial_date: "2027-02-14",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "San Francisco",
            country: "USA",
            venue: "San Francisco Marriott Marquis",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "single-blind",
            paper_format: "IEEE",
            max_pages: 4,
            submission_types: ["regular paper", "demo"],
            h5_index: 78,
            h5_median: 120,
            acceptance_rate: 30.0,
            historical_acceptance_rates: { "2026": 30.0, "2025": 30.0, "2024": 29.0, "2023": 30.5 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.isscc.org/",
            cfp_url: "https://www.isscc.org/call-for-papers",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000132/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Analog", "Digital", "RF", "Power Management", "Data Converters", "Memory"],
            tracks: ["Regular Sessions", "Demo", "Forum", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: "ISSCC 2027 dates estimated from historical patterns. Always held mid-Feb in San Francisco.",
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // VLSI 2026 — Official: vlsisymposium.org
        // Conference: Jun 14–18, 2026, Honolulu, Hawaii
        {
            id: id(),
            name: "IEEE Symposium on VLSI Technology and Circuits",
            short_name: "VLSI",
            year: 2026,
            area: "Hardware",
            rating: "A",
            rating_source: "Community",
            conference_start_date: "2026-06-14",
            conference_end_date: "2026-06-18",
            submission_start_date: "2025-12-02",
            submission_deadline: "2026-01-26",
            notification_date: "2026-03-20",
            camera_ready_date: "2026-04-30",
            workshop_date: "2026-06-14",
            tutorial_date: "2026-06-14",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Honolulu",
            country: "USA",
            venue: "Hilton Hawaiian Village",
            timezone: "Pacific/Honolulu",
            is_virtual: false,
            is_hybrid: false,
            review_type: "single-blind",
            paper_format: "IEEE",
            max_pages: 4,
            submission_types: ["regular paper", "late news"],
            h5_index: 55,
            h5_median: 85,
            acceptance_rate: 28.0,
            historical_acceptance_rates: { "2025": 28.0, "2024": 27.0, "2023": 29.0, "2022": 30.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.vlsisymposium.org/",
            cfp_url: "https://www.vlsisymposium.org/call-for-papers/",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000271/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["VLSI Technology", "Circuit Design", "Devices", "Process", "AI"],
            tracks: ["Technology", "Circuits"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // IEDM 2026 — held annually in December, San Francisco
        {
            id: id(),
            name: "IEEE International Electron Devices Meeting",
            short_name: "IEDM",
            year: 2026,
            area: "Hardware",
            rating: "A*",
            rating_source: "Community",
            conference_start_date: "2026-12-05",
            conference_end_date: "2026-12-09",
            submission_start_date: "2026-05-01",
            submission_deadline: "2026-07-01",
            notification_date: "2026-09-15",
            camera_ready_date: "2026-10-20",
            workshop_date: null,
            tutorial_date: "2026-12-05",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "San Francisco",
            country: "USA",
            venue: "Hilton San Francisco Union Square",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "single-blind",
            paper_format: "IEEE",
            max_pages: 4,
            submission_types: ["regular paper", "late news"],
            h5_index: 62,
            h5_median: 95,
            acceptance_rate: 32.0,
            historical_acceptance_rates: { "2025": 32.0, "2024": 31.0, "2023": 33.0, "2022": 30.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.ieee-iedm.org/",
            cfp_url: "https://www.ieee-iedm.org/call-for-papers",
            proceedings_url: "https://ieeexplore.ieee.org/xpl/conhome/1000205/all-proceedings",
            paper_template_url: "https://www.ieee.org/conferences/publishing/templates.html",
            latex_template_url: null,
            themes: ["Electron Devices", "Transistors", "Memory", "Emerging Devices"],
            tracks: ["Regular Sessions", "Focus Sessions", "Tutorial"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: false,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
        // HOT CHIPS 2026 — Official: hotchips.org
        // Conference: Aug 23–25, Stanford
        {
            id: id(),
            name: "Hot Chips: A Symposium on High Performance Chips",
            short_name: "HOT CHIPS",
            year: 2026,
            area: "Hardware",
            rating: "A",
            rating_source: "Community",
            conference_start_date: "2026-08-23",
            conference_end_date: "2026-08-25",
            submission_start_date: "2026-03-01",
            submission_deadline: "2026-04-08",
            notification_date: "2026-05-15",
            camera_ready_date: "2026-07-17",
            workshop_date: null,
            tutorial_date: "2026-08-23",
            registration_start_date: null,
            registration_end_date: null,
            early_registration_deadline: null,
            abstract_deadline: null,
            city: "Stanford",
            country: "USA",
            venue: "Stanford University, Memorial Auditorium",
            timezone: "America/Los_Angeles",
            is_virtual: false,
            is_hybrid: false,
            review_type: "single-blind",
            paper_format: "Slides/Extended Abstract",
            max_pages: 30,
            submission_types: ["presentation", "poster", "tutorial"],
            h5_index: 40,
            h5_median: 58,
            acceptance_rate: 35.0,
            historical_acceptance_rates: { "2025": 35.0, "2024": 33.0, "2023": 36.0 },
            total_submissions: null,
            total_accepted: null,
            website: "https://www.hotchips.org/",
            cfp_url: "https://www.hotchips.org/call-for-contributions/",
            proceedings_url: "https://hotchips.org/archives/",
            paper_template_url: null,
            latex_template_url: null,
            themes: ["Processors", "AI Accelerators", "Networking", "Memory", "Chiplets"],
            tracks: ["Presentations", "Posters", "Tutorials"],
            keynote_speakers: null,
            proceedings_doi: null,
            publisher: "IEEE",
            open_access: false,
            paper_download_url: null,
            is_favorite: true,
            notes: null,
            color_tag: null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            last_fetched_at: null,
        },
    ];
}

// Cached accessor — ensures IDs are stable across multiple calls
export function getConferences(): Conference[] {
    if (!_cachedConferences) {
        _cachedConferences = buildConferences();
    }
    return _cachedConferences;
}

// Get a conference by its ID
export function getConferenceById(id: number): Conference | undefined {
    return getConferences().find((c) => c.id === id);
}

// Get all unique conference IDs (for static path generation)
export function getAllConferenceIds(): number[] {
    return getConferences().map((c) => c.id);
}
